/* ========================================================================
   TheChocoBot, Product catalogue (100% Eggless)
   Founder: Gunjan Chopra · IHM · VLCC · FSSAI 23321006001296

   Source: Live Zomato menu (May 2026 captures)
   Update this file when menu items, prices or images change.

   Categories on the site:
     signature   The Cookie Tin (hero category)
     teacakes    Loaves & tea cakes
     cookies     Individual cookies (70g)
     cupcakes    Single cupcakes
     brownies    Brownie boxes + Kunafa
     cake_tubs   Single-serve / share cakes in tubs
     iced_coffee Iced beverages
     hampers     Gift hampers / festive
   ======================================================================== */

window.PRODUCTS = [

  // ============ THE COOKIE TIN, HOUSE SIGNATURE ============
  {
    id: "viral-cookie-tin-7",
    name: "Viral Cookie Tin · 7\"",
    category: "signature",
    description: "A premium 7-inch cookie tin, featuring Nutella, dark and milk chocolate.",
    long_description: "The tin Delhi keeps re-ordering. A 7-inch gourmet cookie tin loaded with our signature cookie dough bake, featuring Nutella, dark chocolate and milk chocolate chunks. Hand-stacked, ribbon-tied, hundred-percent eggless. Highly reordered.",
    ingredients: "Flour, cultured butter, brown sugar, Nutella, dark chocolate, milk chocolate, milk, vanilla, baking soda, salt.",
    allergens: ["dairy", "gluten", "nuts"],
    price: 1350,
    weight: "7\" tin, serves 4-6",
    shipping_zone: "pan_india",
    image: "images/products/signature/cookie-dough-tin.jpg",
    bestseller: true,
    viral: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "cookie-tin-5",
    name: "Cookie Tin · 5\"",
    category: "signature",
    description: "A 5-inch gourmet cookie tin, filled with milk chocolate.",
    long_description: "Highly reordered. A 5-inch gourmet cookie tin filled with milk chocolate cookie dough bake. The gifting size, smaller than the viral 7\" but still ridiculous. Eggless, ribbon-tied.",
    ingredients: "Flour, cultured butter, brown sugar, milk chocolate, milk, vanilla, baking soda.",
    allergens: ["dairy", "gluten"],
    price: 800,
    weight: "5\" tin, serves 2-3",
    shipping_zone: "pan_india",
    image: "images/products/signature/cookie-tin-twin.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "everyday-indulgence",
    name: "Everyday Indulgence Cookie Tin",
    category: "signature",
    description: "Cookie tin perfect for 2-3 people. Crisp top, soft centre.",
    long_description: "Highly reordered. A cookie tin sized for 2-3 people: crisp top, soft centre, filled with chocolate. Eggless, baked fresh.",
    ingredients: "Flour, cultured butter, brown sugar, dark chocolate, milk chocolate, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 430,
    weight: "Serves 2-3",
    shipping_zone: "pan_india",
    image: "images/products/signature/cookie-tin-oval.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "mini-cookie-tin",
    name: "Mini Cookie Tin",
    category: "signature",
    description: "Single-serve. Crisp top, soft centre.",
    long_description: "The single-serve cookie tin: crisp top, soft centre, filled with chocolate. The just-because gift. The first taste before you commit to the bigger tin.",
    ingredients: "Flour, cultured butter, brown sugar, milk chocolate, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 220,
    weight: "Single serve",
    shipping_zone: "pan_india",
    image: "images/products/cookies/cookies-05-rustic.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "assorted-cookies",
    name: "Assorted Cookies",
    category: "signature",
    description: "Double Chocolate + Milk Chocolate. The taster.",
    long_description: "A taster of two flavours: double chocolate and milk chocolate cookies. Eggless, hand-stacked, the perfect way to try before you commit to the tin.",
    ingredients: "Flour, cultured butter, brown sugar, dark chocolate, milk chocolate, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 620,
    weight: "Assorted box",
    shipping_zone: "pan_india",
    image: "images/products/cookies/assorted-cookies.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },

  // ============ COOKIES (individual 70g) ============
  {
    id: "triple-chocolate-cookie",
    name: "Triple Chocolate Cookie",
    category: "cookies",
    description: "Soft buttery cookie filled with milk, dark & white chocolate.",
    long_description: "A soft buttery cookie filled with milk chocolate, dark chocolate and white chocolate. 70g, eggless, baked fresh. Crisp top, soft centre.",
    ingredients: "Flour, cultured butter, brown sugar, milk chocolate, dark chocolate, white chocolate, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 160,
    weight: "70g, single cookie",
    shipping_zone: "pan_india",
    image: "images/products/cookies/cookies-03-double-choc.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "milk-chocolate-cookie",
    name: "Milk Chocolate Cookie",
    category: "cookies",
    description: "Soft buttery cookie filled with milk chocolate chunks.",
    long_description: "A soft buttery cookie filled with milk chocolate chunks. 70g, eggless. The classic that started it all.",
    ingredients: "Flour, cultured butter, brown sugar, milk chocolate, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 160,
    weight: "70g, single cookie",
    shipping_zone: "pan_india",
    image: "images/products/cookies/cookies-01-chocchip.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "double-chocolate-cookie",
    name: "Double Chocolate Cookie",
    category: "cookies",
    description: "A buttery, soft and rich chocolate cookie.",
    long_description: "A buttery, soft and rich chocolate cookie. Cocoa-loaded dough with chocolate chunks throughout. 70g, eggless.",
    ingredients: "Flour, cultured butter, brown sugar, cocoa, dark chocolate, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 160,
    weight: "70g, single cookie",
    shipping_zone: "pan_india",
    image: "images/products/cookies/cookies-04-fresh-baked.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },
  {
    id: "new-york-cookie",
    name: "New York Cookie",
    category: "cookies",
    description: "A soft buttery cookie with goodness baked in.",
    long_description: "Our take on the New York-style cookie: thick, chewy, generous chocolate. 70g, eggless.",
    ingredients: "Flour, cultured butter, brown sugar, dark chocolate, milk chocolate, walnuts, milk, vanilla.",
    allergens: ["dairy", "gluten", "nuts"],
    price: 170,
    weight: "70g, single cookie",
    shipping_zone: "pan_india",
    image: "images/products/cookies/new-york-cookie.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days in an airtight container"
  },

  // ============ TEACAKES & LOAVES ============
  {
    id: "marble-tea-cake",
    name: "Marble Tea Cake",
    category: "teacakes",
    description: "A blend of vanilla tea cake and chocolate.",
    long_description: "Two batters, vanilla and chocolate, swirled together so each slice is a marble pattern. Soft, eggless, dangerously snackable.",
    ingredients: "Flour, butter, sugar, cocoa, milk, vanilla, baking powder.",
    allergens: ["dairy", "gluten"],
    price: 240,
    weight: "Loaf",
    shipping_zone: "delhi_only",
    image: "images/products/teacakes/marble-tea-cake.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days at room temperature"
  },
  {
    id: "butter-choco-chip-tea-cake",
    name: "Butter Choco Chip Tea Cake",
    category: "teacakes",
    description: "A rich butter vanilla cake with goodness through every bite.",
    long_description: "A rich butter vanilla loaf studded with dark chocolate chips. Buttery, eggless, the cake to keep on the counter.",
    ingredients: "Flour, cultured butter, sugar, dark chocolate chips, milk, vanilla, baking powder.",
    allergens: ["dairy", "gluten"],
    price: 480,
    weight: "Loaf",
    shipping_zone: "delhi_only",
    image: "images/products/teacakes/butter-choco-chip.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days at room temperature"
  },
  {
    id: "dry-fruit-tea-cake",
    name: "Dry Fruit Tea Cake",
    category: "teacakes",
    description: "A soft, moist vanilla tea cake filled with assorted nuts.",
    long_description: "A soft, moist vanilla tea cake filled with assorted nuts. Freshly baked, eggless, the loaf for slow Sunday mornings.",
    ingredients: "Flour, butter, sugar, mixed nuts (almonds, cashews, raisins), milk, vanilla.",
    allergens: ["dairy", "gluten", "nuts"],
    price: 350,
    weight: "Loaf",
    shipping_zone: "delhi_only",
    image: "images/products/teacakes/dry-fruit-tea-cake.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days at room temperature"
  },
  {
    id: "classic-chocolate-teacake",
    name: "Classic Chocolate Teacake",
    category: "teacakes",
    description: "A classic chocolate teacake filled with chocolate chunks.",
    long_description: "A classic chocolate teacake filled with chocolate chunks. Fresh, soft, eggless.",
    ingredients: "Flour, cocoa, butter, sugar, dark chocolate chunks, milk, vanilla.",
    allergens: ["dairy", "gluten"],
    price: 300,
    weight: "Loaf",
    shipping_zone: "delhi_only",
    image: "images/products/teacakes/classic-chocolate.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days at room temperature"
  },
  {
    id: "banana-walnut-tea-cake",
    name: "Banana Chocolate Walnut Tea Cake",
    category: "teacakes",
    description: "A soft, moist banana cake loaded with chocolate chunks and crushed walnuts.",
    long_description: "Very ripe bananas, dark chocolate chunks, toasted walnuts. Soft, moist, eggless. Best warmed for 8 seconds and eaten with butter.",
    ingredients: "Flour, banana, butter, brown sugar, dark chocolate chunks, walnuts, milk, baking soda, cinnamon.",
    allergens: ["dairy", "gluten", "nuts"],
    price: 420,
    weight: "Loaf",
    shipping_zone: "delhi_only",
    image: "images/products/teacakes/banana-walnut.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days at room temperature"
  },

  // ============ CUPCAKES (single) ============
  {
    id: "blueberry-cupcake",
    name: "Blueberry Cupcake",
    category: "cupcakes",
    description: "A vanilla cupcake filled with luscious blueberry.",
    long_description: "A soft vanilla cupcake filled with a luscious blueberry compote and topped with a swoop of cream cheese. Eggless.",
    ingredients: "Flour, butter, sugar, milk, blueberry compote, cream cheese.",
    allergens: ["dairy", "gluten"],
    price: 130,
    weight: "Single cupcake",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-blueberry.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "mocha-mousse-cupcake",
    name: "Mocha Mousse Cupcake",
    category: "cupcakes",
    description: "A chocolate cupcake decorated with a mocha mousse swirl.",
    long_description: "A chocolate cupcake topped with an airy mocha mousse, espresso-rich and silky. Eggless.",
    ingredients: "Flour, cocoa, butter, sugar, espresso, cream, milk chocolate.",
    allergens: ["dairy", "gluten"],
    price: 130,
    weight: "Single cupcake",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-mocha-mousse.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "chocolate-cupcake",
    name: "Chocolate Cupcake",
    category: "cupcakes",
    description: "Chocolate cupcake topped with Belgian chocolate ganache.",
    long_description: "A deep chocolate cupcake crowned with a thick Belgian chocolate ganache. Eggless.",
    ingredients: "Flour, cocoa, Belgian dark chocolate, butter, sugar, milk, cream.",
    allergens: ["dairy", "gluten"],
    price: 140,
    weight: "Single cupcake",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-chocolate.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "lotus-biscoff-cupcake",
    name: "Lotus Biscoff Cupcake",
    category: "cupcakes",
    description: "Vanilla cupcake filled with Lotus Biscoff.",
    long_description: "A soft vanilla cupcake filled with a Lotus Biscoff core and topped with a swirl of Biscoff buttercream and a crumbled biscuit. Eggless.",
    ingredients: "Flour, butter, sugar, milk, Lotus Biscoff spread, vanilla.",
    allergens: ["dairy", "gluten", "soy"],
    price: 150,
    weight: "Single cupcake",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-biscoff.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "nutella-cupcake",
    name: "Nutella Cupcake",
    category: "cupcakes",
    description: "Chocolate cupcake filled with Nutella.",
    long_description: "A deep chocolate cupcake with a molten Nutella core and a hazelnut-praline buttercream. Eggless.",
    ingredients: "Flour, cocoa, Nutella (hazelnut, cocoa, milk), butter, sugar, milk.",
    allergens: ["dairy", "gluten", "nuts", "soy"],
    price: 150,
    weight: "Single cupcake",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-nutella.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "assorted-cupcake-pack-4",
    name: "Assorted Cupcake · Pack of 4",
    category: "cupcakes",
    description: "Lotus Biscoff + Chocolate cupcakes. The taster pack.",
    long_description: "Four assorted cupcakes: Lotus Biscoff + Chocolate, two of each. The way to try a few without committing to a full box. Eggless.",
    ingredients: "See individual products.",
    allergens: ["dairy", "gluten", "nuts", "soy"],
    price: 560,
    weight: "Pack of 4",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-pack-4.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "assorted-cupcake-box-6",
    name: "Assorted Cupcake · Box of 6",
    category: "cupcakes",
    description: "Lotus Biscoff + Chocolate + more. The full box.",
    long_description: "Six assorted cupcakes across our most-ordered flavours: Lotus Biscoff, Chocolate, Nutella and Mocha. Ribbon-tied, gift-ready. Eggless.",
    ingredients: "See individual products.",
    allergens: ["dairy", "gluten", "nuts", "soy"],
    price: 830,
    weight: "Box of 6",
    shipping_zone: "delhi_only",
    image: "images/products/cakes/cupcake-box-6.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },

  // ============ BROWNIES ============
  {
    id: "assorted-brownie-box",
    name: "Assorted Brownie Box · Box of 4",
    category: "brownies",
    description: "Lotus Biscoff Brownie + Classic Chocolate. The brownie taster.",
    long_description: "A box of 4 brownies: Lotus Biscoff Brownie + Classic Chocolate, two of each. Eggless, dense, fudgy.",
    ingredients: "Dark chocolate, cultured butter, sugar, flour, Lotus Biscoff, cocoa, milk.",
    allergens: ["dairy", "gluten", "soy"],
    price: 620,
    weight: "Box of 4",
    shipping_zone: "delhi_only",
    image: "images/products/brownies/assorted-box.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days refrigerated"
  },
  {
    id: "pistachio-kunafa-brownie",
    name: "Pistachio Kunafa Brownie",
    category: "brownies",
    description: "Decadent chocolate brownie layered with pistachio and kunafa.",
    long_description: "Our decadent chocolate brownie layered with pistachio cream and crisp kunafa. The viral one. Eggless.",
    ingredients: "Dark chocolate, cultured butter, sugar, flour, pistachio, kunafa pastry, milk.",
    allergens: ["dairy", "gluten", "nuts"],
    price: 250,
    weight: "Single brownie",
    shipping_zone: "delhi_only",
    image: "images/products/brownies/brownies-02-stack.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days refrigerated"
  },
  {
    id: "classic-chocolate-brownie",
    name: "Classic Chocolate Brownie",
    category: "brownies",
    description: "A rich, decadent, fudgy chocolate brownie.",
    long_description: "The one. Belgian dark chocolate, cultured butter, just enough flour. Underbaked on purpose so the centre stays gooey. Eggless. Single brownie.",
    ingredients: "Dark chocolate, cultured butter, sugar, flour, cocoa.",
    allergens: ["dairy", "gluten"],
    price: 155,
    weight: "Single brownie",
    shipping_zone: "delhi_only",
    image: "images/products/brownies/brownies-01-fudge.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days refrigerated"
  },
  {
    id: "caramel-brownie",
    name: "Caramel Brownie",
    category: "brownies",
    description: "A rich, decadent fudgy chocolate brownie with caramel.",
    long_description: "Our fudge brownie with thick ribbons of homemade salted caramel swirled through and a finishing flake of sea salt. Eggless.",
    ingredients: "Dark chocolate, cultured butter, sugar, flour, cream, caramel, sea salt.",
    allergens: ["dairy", "gluten"],
    price: 155,
    weight: "Single brownie",
    shipping_zone: "delhi_only",
    image: "images/products/brownies/caramel-brownie.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days refrigerated"
  },
  {
    id: "lotus-biscoff-brownie",
    name: "Lotus Biscoff Brownie",
    category: "brownies",
    description: "A rich, decadent, fudgy chocolate brownie topped with Biscoff.",
    long_description: "Fudge brownie crowned with a Lotus Biscoff layer and crumbled biscuit. Caramelised, slightly cinnamon, very dangerous. Eggless.",
    ingredients: "Dark chocolate, cultured butter, sugar, flour, Lotus Biscoff spread, Biscoff cookies.",
    allergens: ["dairy", "gluten", "soy"],
    price: 165,
    weight: "Single brownie",
    shipping_zone: "delhi_only",
    image: "images/products/brownies/biscoff-brownie.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days refrigerated"
  },
  {
    id: "nutella-brownie",
    name: "Nutella Brownie",
    category: "brownies",
    description: "A rich, decadent, fudgy chocolate brownie with Nutella.",
    long_description: "Fudge brownie with a molten Nutella centre and a hazelnut crumble on top. Eggless.",
    ingredients: "Dark chocolate, cultured butter, sugar, flour, Nutella, hazelnuts.",
    allergens: ["dairy", "gluten", "nuts", "soy"],
    price: 165,
    weight: "Single brownie",
    shipping_zone: "delhi_only",
    image: "images/products/brownies/nutella-brownie.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days refrigerated"
  },

  // ============ CAKE TUBS (single-serve / share) ============
  {
    id: "matilda-cake-tub",
    name: "Matilda Cake Tub",
    category: "cake_tubs",
    description: "A rich chocolate cake topped with super decadent ganache.",
    long_description: "Inspired by the legendary cake. A rich chocolate sponge topped with thick, super-decadent ganache, served in a tub for digging straight in. Eggless. Customisable.",
    ingredients: "Dark chocolate, cocoa, flour, sugar, butter, cream.",
    allergens: ["dairy", "gluten"],
    price: 400,
    weight: "Cake tub",
    shipping_zone: "delhi_only",
    image: "images/products/cake_tubs/matilda.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "vanilla-tres-leches",
    name: "Vanilla Tres Leches",
    category: "cake_tubs",
    description: "A cloud-soft vanilla sponge soaked in three milks.",
    long_description: "A cloud-soft vanilla sponge generously soaked in our three-milk reduction (condensed, evaporated, full-fat), finished with vanilla cream and a cinnamon dust. Eggless adaptation of the classic.",
    ingredients: "Flour, butter, sugar, condensed milk, evaporated milk, full-fat milk, vanilla, cinnamon.",
    allergens: ["dairy", "gluten"],
    price: 400,
    weight: "Cake tub",
    shipping_zone: "delhi_only",
    image: "images/products/cake_tubs/tres-leches.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "2 days refrigerated"
  },
  {
    id: "viral-crunch-cake",
    name: "Viral Crunch Cake",
    category: "cake_tubs",
    description: "Layers of rich chocolate sponge, silky chocolate frosting & crunch.",
    long_description: "Our viral one: layers of rich chocolate sponge, silky chocolate frosting and that addictive crunch on top. Eggless, customisable.",
    ingredients: "Dark chocolate, cocoa, flour, sugar, butter, cream, feuilletine.",
    allergens: ["dairy", "gluten"],
    price: 500,
    weight: "Cake tub",
    shipping_zone: "delhi_only",
    image: "images/products/cake_tubs/viral-crunch.jpg",
    bestseller: true,
    viral: true,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "cookies-cream-cake-tub",
    name: "Cookies & Cream Cake Tub",
    category: "cake_tubs",
    description: "Soft chocolate sponge layered with creamy cookies and cream frosting.",
    long_description: "Soft chocolate sponge layered with creamy cookies & cream frosting and crushed Oreo. Eggless, in a tub.",
    ingredients: "Flour, cocoa, butter, sugar, cream cheese, Oreo cookies, milk.",
    allergens: ["dairy", "gluten", "soy"],
    price: 450,
    weight: "Cake tub",
    shipping_zone: "delhi_only",
    image: "images/products/cake_tubs/cookies-cream.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "3 days refrigerated"
  },
  {
    id: "blueberry-cake-tub",
    name: "Blueberry Cake Tub",
    category: "cake_tubs",
    description: "Light vanilla sponge layered with blueberry compote.",
    long_description: "Light vanilla sponge layered with a tart blueberry compote and a vanilla mousseline. Eggless, in a tub.",
    ingredients: "Flour, butter, sugar, milk, blueberry compote, cream.",
    allergens: ["dairy", "gluten"],
    price: 450,
    weight: "Cake tub",
    shipping_zone: "delhi_only",
    image: "images/products/cake_tubs/blueberry-cake-tub.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "2 days refrigerated"
  },

  // ============ ICED COFFEE (Vikaspuri pickup / delivery) ============
  {
    id: "vanilla-iced-latte",
    name: "Vanilla Iced Latte",
    category: "iced_coffee",
    description: "A smooth, classic iced latte infused with rich vanilla notes.",
    long_description: "A smooth, classic iced latte infused with rich vanilla, topped with cold milk over ice. The everyday.",
    ingredients: "Espresso, milk, vanilla syrup, ice.",
    allergens: ["dairy"],
    price: 180,
    weight: "Iced",
    shipping_zone: "delhi_only",
    image: "images/products/iced_coffee/vanilla-latte.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "Drink within 1 hour"
  },
  {
    id: "iced-mocha",
    name: "Iced Mocha",
    category: "iced_coffee",
    description: "A decadent blend of intense espresso and rich dark chocolate.",
    long_description: "A decadent blend of intense espresso and rich dark chocolate, served over ice with cold milk.",
    ingredients: "Espresso, dark chocolate, milk, ice.",
    allergens: ["dairy"],
    price: 190,
    weight: "Iced",
    shipping_zone: "delhi_only",
    image: "images/products/iced_coffee/iced-mocha.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "Drink within 1 hour"
  },
  {
    id: "coconut-water-iced-americano",
    name: "Coconut Water Iced Americano",
    category: "iced_coffee",
    description: "A refreshing twist on the classic Americano, bold espresso poured over coconut water.",
    long_description: "Our refresher. Bold espresso poured over chilled coconut water. Bright, light, hydrating.",
    ingredients: "Espresso, coconut water, ice.",
    allergens: [],
    price: 190,
    weight: "Iced",
    shipping_zone: "delhi_only",
    image: "images/products/iced_coffee/americano.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "Drink within 1 hour"
  },
  {
    id: "salted-caramel-iced-latte",
    name: "Salted Caramel Iced Latte",
    category: "iced_coffee",
    description: "A rich indulgent iced latte with buttery caramel sweetness.",
    long_description: "A rich, indulgent iced latte with buttery caramel sweetness and a finishing flake of sea salt.",
    ingredients: "Espresso, milk, salted caramel sauce, ice, sea salt.",
    allergens: ["dairy"],
    price: 230,
    weight: "Iced",
    shipping_zone: "delhi_only",
    image: "images/products/iced_coffee/salted-caramel.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "Drink within 1 hour"
  },
  {
    id: "tiramisu-iced-latte",
    name: "Tiramisu Iced Latte",
    category: "iced_coffee",
    description: "Inspired by classic Italian dessert, bold espresso layered with mascarpone cream.",
    long_description: "Inspired by the classic Italian dessert: bold espresso layered with a whipped mascarpone cream and dusted with cocoa.",
    ingredients: "Espresso, milk, mascarpone, sugar, cocoa.",
    allergens: ["dairy"],
    price: 250,
    weight: "Iced",
    shipping_zone: "delhi_only",
    image: "images/products/iced_coffee/tiramisu.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "Drink within 1 hour"
  },
  {
    id: "biscoff-iced-latte",
    name: "Biscoff Iced Latte",
    category: "iced_coffee",
    description: "Creamy iced latte blended with indulgent Biscoff spread.",
    long_description: "A creamy iced latte blended with indulgent Biscoff spread, topped with a Biscoff crumb.",
    ingredients: "Espresso, milk, Lotus Biscoff spread, ice.",
    allergens: ["dairy", "soy"],
    price: 240,
    weight: "Iced",
    shipping_zone: "delhi_only",
    image: "images/products/iced_coffee/biscoff.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "Drink within 1 hour"
  },

  // ============ HAMPERS (kept from earlier brief) ============
  {
    id: "festive-hamper-small",
    name: "Small Festive Hamper",
    category: "hampers",
    description: "Two boxes, ribbon, a handwritten note.",
    long_description: "A small but mighty gift: one Mini Cookie Tin + one Assorted Brownie Box, kraft-boxed, satin-ribboned, with a handwritten card. Customisable note up to 40 chars.",
    ingredients: "See individual products.",
    allergens: ["dairy", "gluten"],
    price: 1500,
    weight: "Hamper",
    shipping_zone: "pan_india",
    image: "images/hampers/hampers-01-ribbon.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days"
  },
  {
    id: "festive-hamper-large",
    name: "Large Festive Hamper",
    category: "hampers",
    description: "Four boxes, dry fruit, greeting card. The one people remember.",
    long_description: "The full spread: Cookie Tin 5\" + Assorted Brownie Box + a chocolate marble tea cake + 200g premium dry fruit, with a greeting card and satin ribbon. Comes in a stitched cloth hamper bag.",
    ingredients: "See individual products. Includes mixed dry fruit (almonds, cashews, pistachios, dates).",
    allergens: ["dairy", "gluten", "nuts"],
    price: 2800,
    weight: "Large hamper",
    shipping_zone: "pan_india",
    image: "images/hampers/hampers-06-assorted-box.jpg",
    bestseller: true,
    in_stock: true,
    eggless: true,
    shelf_life: "5 days"
  },
  {
    id: "diwali-hamper",
    name: "Diwali Special Hamper",
    category: "hampers",
    description: "Brass tin, signature flavours, hand-tied with kalava.",
    long_description: "A limited Diwali hamper: brass tin of signature cookies + pistachio kunafa brownies + a small box of premium dry fruit, finished with traditional kalava and a diya. Available October–November only.",
    ingredients: "See individual products.",
    allergens: ["dairy", "gluten", "nuts"],
    price: 2200,
    weight: "Festive hamper",
    shipping_zone: "pan_india",
    image: "images/hampers/hampers-03-festive.jpg",
    bestseller: false,
    in_stock: true,
    eggless: true,
    seasonal: true,
    shelf_life: "5 days"
  }
];

// ============ CATEGORIES ============
window.CATEGORIES = [
  { id: "all",         name: "Everything" },
  { id: "signature",   name: "Cookie Tin" },
  { id: "cookies",     name: "Cookies" },
  { id: "teacakes",    name: "Tea Cakes" },
  { id: "cupcakes",    name: "Cupcakes" },
  { id: "brownies",    name: "Brownies" },
  { id: "cake_tubs",   name: "Cake Tubs" },
  { id: "iced_coffee", name: "Iced Coffee" },
  { id: "hampers",     name: "Hampers" }
];

// ============ HELPERS ============
window.findProduct = (id) => window.PRODUCTS.find(p => p.id === id);
window.productsByCategory = (catId) =>
  (!catId || catId === "all") ? window.PRODUCTS : window.PRODUCTS.filter(p => p.category === catId);
window.featuredProducts = (count = 4) =>
  window.PRODUCTS.filter(p => p.bestseller).slice(0, count);
window.signatureProducts = () =>
  window.PRODUCTS.filter(p => p.category === "signature");
window.viralProduct = () =>
  window.PRODUCTS.find(p => p.viral);
window.formatPrice = (n) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
